# Generated by Django 6.0.5 on 2026-06-19 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_options_alter_room_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='room',
            name='unique_chat_room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='message',
            name='edited_at',
        ),
        migrations.AlterField(
            model_name='room',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('user1', 'user2'), name='unique_room_pair'),
        ),
    ]
